### ISSUE TITLE
怎么debug

### ISSUE THREAD

**Issue by zhangzhishan** [easychen/aiapi#6]
用浏览器可以访问claude 内容，但是用了这个之后api调用没有结果，超时，请问可以怎么debug嘛？
m1 mac，但是arm 版本的软件打不开，所以用的x64版本。不知道和这个有没有关系。

**Comment by zhangzhishan** [comment]
<img width="784" alt="image" src="https://github.com/easychen/aiapi/assets/5714057/b1b93183-67b8-4d67-8beb-065f088ad957">

直接访问api 显示可以work。

**Comment by easychen** [comment]
如果你的网络不在Claude支持的范围，那么可能需要检查下代理配置是否正确。

**Comment by zhangzhishan** [comment]
试了用postman发送，返回的是空。我的网络可以直接连Claude，不需要代理。

> 如果你的网络不在Claude支持的范围，那么可能需要检查下代理配置是否正确。

**Comment by zhongweili** [comment]
+1

**Comment by puteulanus** [comment]
遇到了同样的问题，进入 AiAPI.app/Contents/MacOS 用终端执行 ./AiAPI 能看到日志
```
Express server listening at http://localhost:3456
Error: Forbidden
    at onopen (/Applications/AiAPI.app/Contents/Resources/app.asar/src/index.js:377:17)
    at fetchSSE (/Applications/AiAPI.app/Contents/Resources/app.asar/src/index.js:485:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Applications/AiAPI.app/Contents/Resources/app.asar/src/index.js:263:22
```
发现程序不知道为什么不走软路由上 passwall 的分流规则，手动设置 passwall 的 http proxy 之后正常工作了

中间试图用 Charles 调试的时候发现程序似乎也不认 Charles 添加到系统的根证书
